### ISSUE TITLE
editing of plugins not possible (Exception in LanguageService.php)

### ISSUE THREAD

**Issue by nabossha** [derhansen/sf_event_mgt#1190]
### Extension version
- 7.3.3  / dev-develop

### Short problem description
once the extension is installed, editing an element of type "plugin" (list) in page or list-mode produces this error:
![image](https://github.com/derhansen/sf_event_mgt/assets/3851681/caa526ee-b641-48f9-86a8-1ce8b83dac09)

`PHP Warning: Array to string conversion in /var/www/html/vendor/typo3/cms-core/Classes/Localization/LanguageService.php line 178`

**once the extension is removed, editing of plugin-CEs works again.**

**update:**
 adjusting registerPlugin in tt_content as follows fixes the error: (omitting '**sf_event_mgt**' as group-argument)
 
````
// Register plugin
    ExtensionUtility::registerPlugin(
        'SfEventMgt',
        $pluginName,
        'LLL:EXT:sf_event_mgt/Resources/Private/Language/locallang_be.xlf:plugin.' . strtolower($pluginName) . '.title',
        'ext-sfeventmgt-default'
    );
```` 

### Steps to reproduce
1. install one of the above extension-versions

### Server configuration
- DDEV using nginx

**TYPO3 version:** 12.4.10

**PHP version:** 8.2

**Comment by derhansen** [comment]
Sorry, I'm not able to reproduce the problem. The group Parameter must be string, which it is. Also the group parameter is required for the extension to allow grouping of all plugins.

Please try to delete the content element and insert a new one from scratch. 

If the problem still occours, please provide a fill stacktrace.

**Comment by nabossha** [comment]
i can neither edit or add a plugin, the error appears on new elements as well. 

here you go
`````
Thu, 01 Feb 2024 17:27:48 +0100 [CRITICAL] request="45905acc06d3d" component="TYPO3.CMS.Core.Error.DebugExceptionHandler": Core: Exception handler (WEB: BE): TYPO3\CMS\Core\Error\Exception, code #1476107295, file /var/www/html/vendor/typo3/cms-core/Classes/Error/ErrorHandler.php, line 138: PHP Warning: Array to string conversion in /var/www/html/vendor/typo3/cms-core/Classes/Localization/LanguageService.php line 178- Exception: PHP Warning: Array to string conversion in /var/www/html/vendor/typo3/cms-core/Classes/Localization/LanguageService.php line 178, in file /var/www/html/vendor/typo3/cms-core/Classes/Error/ErrorHandler.php:138 - {"mode":"WEB","application_mode":"BE","exception_class":"TYPO3\\CMS\\Core\\Error\\Exception","exception_code":1476107295,"file":"/var/www/html/vendor/typo3/cms-core/Classes/Error/ErrorHandler.php","line":138,"message":"PHP Warning: Array to string conversion in /var/www/html/vendor/typo3/cms-core/Classes/Localization/LanguageService.php line 178","request_url":"https://kvz-schule-lts12.ddev.site/typo3/record/edit?token=--AnonymizedToken--&edit%5Btt_content%5D%5B-3594%5D=new&returnUrl=/typo3/module/web/layout?token%3D--AnonymizedToken--%26id%3D27%26&defVals%5Btt_content%5D%5BCType%5D=list&defVals%5Btt_content%5D%5Blist_type%5D=sfeventmgt_pieventlist&defVals%5Btt_content%5D%5Btx_gridelements_columns%5D=0&defVals%5Btt_content%5D%5BcolPos%5D=0&defVals%5Btt_content%5D%5Bsys_language_uid%5D=0","exception":"TYPO3\\CMS\\Core\\Error\\Exception: PHP Warning: Array to string conversion in /var/www/html/vendor/typo3/cms-core/Classes/Localization/LanguageService.php line 178 in /var/www/html/vendor/typo3/cms-core/Classes/Error/ErrorHandler.php:138\nStack trace:\n#0 /var/www/html/vendor/typo3/cms-core/Classes/Localization/LanguageService.php(178): TYPO3\\CMS\\Core\\Error\\ErrorHandler->handleError(2, 'Array to string...', '/var/www/html/v...', 178)\n#1 /var/www/html/vendor/typo3/cms-backend/Classes/Form/FormDataProvider/TcaSelectItems.php(227): TYPO3\\CMS\\Core\\Localization\\LanguageService->sL(Array)\n#2 /var/www/html/vendor/typo3/cms-backend/Classes/Form/FormDataProvider/TcaSelectItems.php(122): TYPO3\\CMS\\Backend\\Form\\FormDataProvider\\TcaSelectItems->groupAndSortItems(Array, Array, Array)\n#3 /var/www/html/vendor/typo3/cms-backend/Classes/Form/FormDataGroup/OrderedProviderList.php(73): TYPO3\\CMS\\Backend\\Form\\FormDataProvider\\TcaSelectItems->addData(Array)\n#4 /var/www/html/vendor/typo3/cms-backend/Classes/Form/FormDataGroup/TcaDatabaseRecord.php(40): TYPO3\\CMS\\Backend\\Form\\FormDataGroup\\OrderedProviderList->compile(Array)\n#5 /var/www/html/vendor/typo3/cms-backend/Classes/Form/FormDataCompiler.php(108): TYPO3\\CMS\\Backend\\Form\\FormDataGroup\\TcaDatabaseRecord->compile(Array)\n#6 /var/www/html/vendor/typo3/cms-backend/Classes/Controller/EditDocumentController.php(1112): TYPO3\\CMS\\Backend\\Form\\FormDataCompiler->compile(Array, Object(TYPO3\\CMS\\Backend\\Form\\FormDataGroup\\TcaDatabaseRecord))\n#7 /var/www/html/vendor/typo3/cms-backend/Classes/Controller/EditDocumentController.php(981): TYPO3\\CMS\\Backend\\Controller\\EditDocumentController->makeEditForm(Object(TYPO3\\CMS\\Core\\Http\\ServerRequest), Object(TYPO3\\CMS\\Backend\\Template\\ModuleTemplate))\n#8 /var/www/html/vendor/typo3/cms-backend/Classes/Controller/EditDocumentController.php(398): TYPO3\\CMS\\Backend\\Controller\\EditDocumentController->main(Object(TYPO3\\CMS\\Backend\\Template\\ModuleTemplate), Object(TYPO3\\CMS\\Core\\Http\\ServerRequest))\n#9 /var/www/html/vendor/typo3/cms-backend/Classes/Http/RouteDispatcher.php(77): TYPO3\\CMS\\Backend\\Controller\\EditDocumentController->mainAction(Object(TYPO3\\CMS\\Core\\Http\\ServerRequest))\n#10 /var/www/html/vendor/typo3/cms-backend/Classes/Http/RequestHandler.php(104): TYPO3\\CMS\\Backend\\Http\\RouteDispatcher->dispatch(Object(TYPO3\\CMS\\Core\\Http\\ServerRequest))\n#11 /var/www/html/vendor/typo3/cms-core/Classes/Middleware/ResponsePropagation.php(34): TYPO3\\CMS\\Backend\\Http\\RequestHandler->handle(Object(TYPO3\\CMS\\Core\\Http\\ServerRequest))\n#12 /var/www/html/vendor/typo3/cms-core/Classes/Http/MiddlewareDispatcher.php(162): TYPO3\\CMS\\Core\\Middleware\\ResponsePropagation->process(Object(TYPO3\\CMS\\Core\\Http\\ServerRequest), Object(TYPO3\\CMS\\Backend\\Http\\RequestHandler))\n#13 /var/www/html/vendor/typo3/cms-backend/Classes/Middleware/SiteResolver.php(64): Psr\\Http\\Server\\RequestHandlerInterface@anonymous->handle(Object(TYPO3\\CMS\\Core\\Http\\ServerRequest))\n#14 /var/www/html/vendor/typo3/cms-core/Classes/Http/MiddlewareDispatcher.php(162): TYPO3\\CMS\\Backend\\Middleware\\SiteResolver->process(Object(TYPO3\\CMS\\Core\\Http\\ServerRequest), Object(Psr\\Http\\Server\\RequestHandlerInterface@anonymous))\n#15 /var/www/html/vendor/typo3/cms-backend/Classes/Middleware/SudoModeInterceptor.php(51): Psr\\Http\\Server\\RequestHandlerInterface@anonymous->handle(Object(TYPO3\\CMS\\Core\\Http\\ServerRequest))\n#16 /var/www/html/vendor/typo3/cms-core/Classes/Http/MiddlewareDispatcher.php(162): TYPO3\\CMS\\Backend\\Middleware\\SudoModeInterceptor->process(Object(TYPO3\\CMS\\Core\\Http\\ServerRequest), Object(Psr\\Http\\Server\\RequestHandlerInterface@anonymous))\n#17 /var/www/html/vendor/typo3/cms-backend/Classes/Middleware/AdditionalResponseHeaders.php(37): Psr\\Http\\Server\\RequestHandlerInterface@anonymous->handle(Object(TYPO3\\CMS\\Core\\Http\\ServerRequest))\n#18 /var/www/html/vendor/typo3/cms-core/Classes/Http/MiddlewareDispatcher.php(162): TYPO3\\CMS\\Backend\\Middleware\\AdditionalResponseHeaders->process(Object(TYPO3\\CMS\\Core\\Http\\ServerRequest), Object(Psr\\Http\\Server\\RequestHandlerInterface@anonymous))\n#19 /var/www/html/vendor/typo3/cms-backend/Classes/Middleware/ContentSecurityPolicyHeaders.php(50): Psr\\Http\\Server\\RequestHandlerInterface@anonymous->handle(Object(TYPO3\\CMS\\Core\\Http\\ServerRequest))\n#20 /var/www/html/vendor/typo3/cms-core/Classes/Http/MiddlewareDispatcher.php(162): TYPO3\\CMS\\Backend\\Middleware\\ContentSecurityPolicyHeaders->process(Object(TYPO3\\CMS\\Core\\Http\\ServerRequest), Object(Psr\\Http\\Server\\RequestHandlerInterface@anonymous))\n#21 /var/www/html/vendor/typo3/cms-backend/Classes/Middleware/OutputCompression.php(43): Psr\\Http\\Server\\RequestHandlerInterface@anonymous->handle(Object(TYPO3\\CMS\\Core\\Http\\ServerRequest))\n#22 /var/www/html/vendor/typo3/cms-core/Classes/Http/MiddlewareDispatcher.php(162): TYPO3\\CMS\\Backend\\Middleware\\OutputCompression->process(Object(TYPO3\\CMS\\Core\\Http\\ServerRequest), Object(Psr\\Http\\Server\\RequestHandlerInterface@anonymous))\n#23 /var/www/html/vendor/typo3/cms-backend/Classes/Middleware/BackendModuleValidator.php(72): Psr\\Http\\Server\\RequestHandlerInterface@anonymous->handle(Object(TYPO3\\CMS\\Core\\Http\\ServerRequest))\n#24 /var/www/html/vendor/typo3/cms-core/Classes/Http/MiddlewareDispatcher.php(162): TYPO3\\CMS\\Backend\\Middleware\\BackendModuleValidator->process(Object(TYPO3\\CMS\\Core\\Http\\ServerRequest), Object(Psr\\Http\\Server\\RequestHandlerInterface@anonymous))\n#25 /var/www/html/vendor/typo3/cms-backend/Classes/Middleware/BackendUserAuthenticator.php(159): Psr\\Http\\Server\\RequestHandlerInterface@anonymous->handle(Object(TYPO3\\CMS\\Core\\Http\\ServerRequest))\n#26 /var/www/html/vendor/typo3/cms-core/Classes/Http/MiddlewareDispatcher.php(162): TYPO3\\CMS\\Backend\\Middleware\\BackendUserAuthenticator->process(Object(TYPO3\\CMS\\Core\\Http\\ServerRequest), Object(Psr\\Http\\Server\\RequestHandlerInterface@anonymous))\n#27 /var/www/html/vendor/typo3/cms-reactions/Classes/Http/Middleware/ReactionResolver.php(57): Psr\\Http\\Server\\RequestHandlerInterface@anonymous->handle(Object(TYPO3\\CMS\\Core\\Http\\ServerRequest))\n#28 /var/www/html/vendor/typo3/cms-core/Classes/Http/MiddlewareDispatcher.php(162): TYPO3\\CMS\\Reactions\\Http\\Middleware\\ReactionResolver->process(Object(TYPO3\\CMS\\Core\\Http\\ServerRequest), Object(Psr\\Http\\Server\\RequestHandlerInterface@anonymous))\n#29 /var/www/html/vendor/typo3/cms-core/Classes/Middleware/RequestTokenMiddleware.php(71): Psr\\Http\\Server\\RequestHandlerInterface@anonymous->handle(Object(TYPO3\\CMS\\Core\\Http\\ServerRequest))\n#30 /var/www/html/vendor/typo3/cms-core/Classes/Http/MiddlewareDispatcher.php(162): TYPO3\\CMS\\Core\\Middleware\\RequestTokenMiddleware->process(Object(TYPO3\\CMS\\Core\\Http\\ServerRequest), Object(Psr\\Http\\Server\\RequestHandlerInterface@anonymous))\n#31 /var/www/html/vendor/typo3/cms-backend/Classes/Middleware/BackendRouteInitialization.php(80): Psr\\Http\\Server\\RequestHandlerInterface@anonymous->handle(Object(TYPO3\\CMS\\Core\\Http\\ServerRequest))\n#32 /var/www/html/vendor/typo3/cms-core/Classes/Http/MiddlewareDispatcher.php(162): TYPO3\\CMS\\Backend\\Middleware\\BackendRouteInitialization->process(Object(TYPO3\\CMS\\Core\\Http\\ServerRequest), Object(Psr\\Http\\Server\\RequestHandlerInterface@anonymous))\n#33 /var/www/html/vendor/typo3/cms-backend/Classes/Middleware/ContentSecurityPolicyReporter.php(41): Psr\\Http\\Server\\RequestHandlerInterface@anonymous->handle(Object(TYPO3\\CMS\\Core\\Http\\ServerRequest))\n#34 /var/www/html/vendor/typo3/cms-core/Classes/Http/MiddlewareDispatcher.php(162): TYPO3\\CMS\\Backend\\Middleware\\ContentSecurityPolicyReporter->process(Object(TYPO3\\CMS\\Core\\Http\\ServerRequest), Object(Psr\\Http\\Server\\RequestHandlerInterface@anonymous))\n#35 /var/www/html/vendor/typo3/cms-backend/Classes/Middleware/ForcedHttpsBackendRedirector.php(55): Psr\\Http\\Server\\RequestHandlerInterface@anonymous->handle(Object(TYPO3\\CMS\\Core\\Http\\ServerRequest))\n#36 /var/www/html/vendor/typo3/cms-core/Classes/Http/MiddlewareDispatcher.php(162): TYPO3\\CMS\\Backend\\Middleware\\ForcedHttpsBackendRedirector->process(Object(TYPO3\\CMS\\Core\\Http\\ServerRequest), Object(Psr\\Http\\Server\\RequestHandlerInterface@anonymous))\n#37 /var/www/html/vendor/typo3/cms-backend/Classes/Middleware/LockedBackendGuard.php(71): Psr\\Http\\Server\\RequestHandlerInterface@anonymous->handle(Object(TYPO3\\CMS\\Core\\Http\\ServerRequest))\n#38 /var/www/html/vendor/typo3/cms-core/Classes/Http/MiddlewareDispatcher.php(162): TYPO3\\CMS\\Backend\\Middleware\\LockedBackendGuard->process(Object(TYPO3\\CMS\\Core\\Http\\ServerRequest), Object(Psr\\Http\\Server\\RequestHandlerInterface@anonymous))\n#39 /var/www/html/vendor/typo3/cms-core/Classes/Middleware/NormalizedParamsAttribute.php(41): Psr\\Http\\Server\\RequestHandlerInterface@anonymous->handle(Object(TYPO3\\CMS\\Core\\Http\\ServerRequest))\n#40 /var/www/html/vendor/typo3/cms-core/Classes/Http/MiddlewareDispatcher.php(162): TYPO3\\CMS\\Core\\Middleware\\NormalizedParamsAttribute->process(Object(TYPO3\\CMS\\Core\\Http\\ServerRequest), Object(Psr\\Http\\Server\\RequestHandlerInterface@anonymous))\n#41 /var/www/html/vendor/typo3/cms-core/Classes/Middleware/VerifyHostHeader.php(55): Psr\\Http\\Server\\RequestHandlerInterface@anonymous->handle(Object(TYPO3\\CMS\\Core\\Http\\ServerRequest))\n#42 /var/www/html/vendor/typo3/cms-core/Classes/Http/MiddlewareDispatcher.php(162): TYPO3\\CMS\\Core\\Middleware\\VerifyHostHeader->process(Object(TYPO3\\CMS\\Core\\Http\\ServerRequest), Object(Psr\\Http\\Server\\RequestHandlerInterface@anonymous))\n#43 /var/www/html/vendor/typo3/cms-core/Classes/Http/MiddlewareDispatcher.php(70): Psr\\Http\\Server\\RequestHandlerInterface@anonymous->handle(Object(TYPO3\\CMS\\Core\\Http\\ServerRequest))\n#44 /var/www/html/vendor/typo3/cms-core/Classes/Http/AbstractApplication.php(80): TYPO3\\CMS\\Core\\Http\\MiddlewareDispatcher->handle(Object(TYPO3\\CMS\\Core\\Http\\ServerRequest))\n#45 /var/www/html/vendor/typo3/cms-backend/Classes/Http/Application.php(58): TYPO3\\CMS\\Core\\Http\\AbstractApplication->handle(Object(TYPO3\\CMS\\Core\\Http\\ServerRequest))\n#46 /var/www/html/vendor/typo3/cms-core/Classes/Http/AbstractApplication.php(92): TYPO3\\CMS\\Backend\\Http\\Application->handle(Object(TYPO3\\CMS\\Core\\Http\\ServerRequest))\n#47 /var/www/html/web/typo3/index.php(20): TYPO3\\CMS\\Core\\Http\\AbstractApplication->run()\n#48 /var/www/html/web/typo3/index.php(21): {closure}()\n#49 {main}"}

````
